### ISSUE TITLE
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[NSCFArray removeObjectAtIndex:]: mutating method sent to immutable object'

### ISSUE THREAD

**Issue by kstavland** [juretta/objc-stomp#1]
When i try to run the code i get the following error:

**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '**\* -[NSCFArray removeObjectAtIndex:]: mutating method sent to immutable object'

I get to connect to the server, and have just subscribed to a queue and started to receive messages when the error happens. Does anyone here know what it could be, or guide me in the righ direction ?

**Comment by juretta** [comment]
Create a mutableCopy for the message contents array (Closed by 99e025bf919b2689a969be3f8f4a0312c4b9b8d7).

**Comment by juretta** [comment]
Hi,

commit 99e025bf contains a fix that might resolve your issue.

FYI: The http://github.com/juretta/fpcc contains example code (objc-stomp in an iPhone client, ruby client and Java webapp).

Cheers,
Stefan

**Comment by kstavland** [comment]
Can you explain that a little more? I can`t really narrow down where in the code the error is. It would be much aprichiated if i could get some help finding where in the code the error happens and how to fix it.

In your source page it also sais update to AsynSocket R78. Is the code only usable for the R78 repostory of AsynSocket or can i uses the newest one? (think its something around R92)

Thanks a lot for the help so far.

**Comment by juretta** [comment]
Just use the latest version of objc-stomp that includes the fix in commit 99e025b.

The updated AsyncSocket is already part of the project. The commit message is probably a little bit misleading: Should have been "Updated AsyncSocket to r78" (i.e. it's already done).

Cheers,
Stefan

**Comment by kstavland** [comment]
Sorry for the newbies questions, but i am woundering about a few more things.

The link you gave me showed how i could fix my problem, and by going into my source code and adding mutableCopy i get the code to run without problems so thanks a lot ! 
But i think its a little strange that i had to fix it myself, since you have allready checked in that code here to bithub. I tought that if i went to http://github.com/juretta/objc-stomp and press download source i would get the newest code from you. Aint that correct?

Also the reason why i asked about AsyncSocket is that i am guessing that AsyncSocket that is in your source code is r78, but if you go to http://code.google.com/p/cocoaasyncsocket/source/checkout you can checkout r93. Should i just use the AsynscSocket that follows your source code or should i go get the newest on from google.code?

I am not very used to using githug or google code and subversion :( So having a little trouble navigation and finding the right places to download the right code...
