### ISSUE TITLE
ReplyTo in the message-header

### ISSUE THREAD

**Issue by ghost** [juretta/objc-stomp#12]
Is it possible to add an ReplyTo value to the message header ? Which key should be used for this ?

Thank you

**Comment by juretta** [comment]
Sure, that would be a header with a key named `reply-to` if you use Stomp messages with JMS message semantics.

Use `- (void)sendMessage:(NSString *)theMessage toDestination:(NSString *)destination withHeaders:(NSDictionary*)headers` and add the `reply-to` key-value pair to the headers dictionary.

**Comment by juretta** [comment]
Hi @DanielBocksteger, did this answer your question?

**Comment by ghost** [comment]
Hi I'm really sorry that i didn't answered your question. Yes this works perfect for my situation. Thanks a lot.

**Comment by juretta** [comment]
No worries, glad that it works! :)
