### ISSUE TITLE
how to notify if a message received from server and application is in inactive state?? is it possible to show a notification to user by defaults notification in ios?

### ISSUE THREAD

**Issue by abdulrehman90** [juretta/objc-stomp#14]

**Comment by juretta** [comment]
Hi,

Can you elaborate on what you mean by "inactive state"?
And do you expect the notification to be shown by the library or are you looking for a way to show this notification to your users and need a way to hook into the library?

Cheers,
Stefan

**Comment by abdulrehman90** [comment]
Hi
thanks for your replay. i am stuck in a situation  i want if application is in background means application running but not On front and a message received. this library do nothing in that condition because application in background. as soon as i launch it again it display me a received message. but i want it should show a notification " A message Received" even application may in background.. waiting for ur's reply
thanks

**Comment by abdulrehman90** [comment]
just like push notification or local notification in iOS.. 
message received and shown even the app in background (not on front)

**Comment by abdulrehman90** [comment]
need ur help bro

**Comment by juretta** [comment]
I don't think the sockets are set correctly to work in the background and according to http://developer.apple.com/library/ios/#documentation/iphone/conceptual/iphoneosprogrammingguide/ManagingYourApplicationsFlow/ManagingYourApplicationsFlow.html I don't think the a use case for keeping open the socket connection in the background would be covered by the acceptable use cases.
