### ISSUE TITLE
Should be able to establish a connection with no username/password

### ISSUE THREAD

**Issue by ghost** [juretta/objc-stomp#3]
My application connects to anonymous login Stomp server. 

Currently I provide nil nil for the username and password parameters on the init method.

However, since an update to ActiveMQ's anonymous user security, the CONNECT frame with username: and password: headers set as NULL is seen as an authentication attempt instead of anonymous access and fails as a result.

Therefore, should we provide a second init method that allows you to not specify user/pass and therefore send a connect frame with those headers not sent?

**Comment by juretta** [comment]
Hi, I've created a branch with the change you suggested:
http://github.com/juretta/objc-stomp/tree/anonymous

Is this what you are after?

Thanks for your suggestion.

Cheers,
Stefan

**Comment by andybee** [comment]
Oops, logged in under the wrong account on GitHub! But yes, this was what I was after, thank you. Will give it a proper test in the next day or so.
