### ISSUE TITLE
STOMP listener consumes 2MB RAM on iPhone OS 4.1

### ISSUE THREAD

**Issue by johnboyer** [juretta/objc-stomp#5]
We have been doing some memory analysis of our iPhone app. We’ve found that one STOMP listener consumes about 2MB of RAM. 

Do you have any suggestions to reduce the memory footprint of a STOMP listener?

Thank you for your time.

Regards,
John Boyer

**Comment by juretta** [comment]
Hi John,

I had a look at a demo project of mine that is using much less memory (~ 1MB overall).
So I'm not quite sure why this is so much higher for you for the listener alone.
Would it be possible for you to send me the recorded Instruments session?

As a sidenote: I did update the AsyncSocket library from r78 to r101 in #58abef6a4ef5f1c0419170cc014f9938c476c7e2 
I doubt that this will fix the problem but you might want to give it a try.

Regards,
Stefan
